config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'doctors#index'
  resources :doctors, :patients

  get "doctors", to: "doctors#index"
  get "doctors/:id", to: "doctors#show"
  get "doctors/new", to: "doctors#new"
  get "patients/new", to: "patients#new"
  get "doctors/:id/edit", to: "doctors#edit"

  post "doctors", to: "doctors#create"
  post "patients", to: "patients#create"

  patch "doctors", to: "doctors#update"

  delete "doctors/:id", to: "doctors#destroy"
  delete "patients/:id", to: "patients#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :patients, dependent: :destroy
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :doctor
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
    
    def index
        @doctors = Doctor.all
    end

    def show
        @doctor = Doctor.find(params[:id])
        @patients = @doctor.patients
    end

    def new
        @doctor = Doctor.new
    end

    def create
        Doctor.create(params.require(:doctor).permit(:name, :dep))
        redirect_to doctors_path
    end

    def edit
        @doctor = Doctor.find(params[:id])
    end

    def update
        doctor = Doctor.find(params[:id])
        doctor.update(params.require(:doctor).permit(:name, :dep))
        redirect_to doctor
    end

    def destroy
        Doctor.find(params[:id]).destroy
        redirect_to doctors_path
    end
    
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

    def new
        @doctor = Doctor.find(params[:doctor_id])
        @patient = Patient.new
    end

    def create
        puts params
        doctor = Doctor.find(params[:patient][:doctor_id])
        Patient.create(params.require(:patient).permit(:mrn, :name, :age, :gen, :bed_no, :doctor_id))
        redirect_to doctor
    end

    def destroy
        Patient.find(params[:id]).destroy
        redirect_to patients_path
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/doctors/_form.html.erb
<%= form_for @doctor do |n| %>
<div class="column">
    <form class="col s12">
        <div class="input-field col s4">
            <%= n.label :name, "Physician's Name" %>
            <%= n.text_field :name %>
        </div>
        <div class="input-field col s4">
            <%= n.label :dep, "Physician's Department" %>
            <%= n.text_field :dep %>
        </div>
    </form>
    <%= n.submit "Submit", :class => "btn waves-effect waves-light"%>
</div>
<% end %>

app/views/doctors/edit.html.erb
<div class="container">
    <p class="flow-text">Edit Dr. <%= @doctor.name %></p>
    <%= render 'doctors/form'%>
</div>

app/views/doctors/index.html.erb
<div class="container">
<p class="flow-text">Physicians Dashboard</p>
<%= link_to content_tag('i', 'add', class: 'small material-icons'), new_doctor_path, data: {confirm:"Add a new physician?"} %>
<br/>
<br/>

<table class="highlight">
    <tr>
        <th>Physician's Name</th>
        <th>Department</th>
        <th>Joining Date</th>
    </tr>

    <% @doctors.each do |doctor| %>
        <tr>
            <td>Dr. <%= doctor.name %></td>
            <td><%= doctor.dep %></td>
            <td><%= doctor.created_at.strftime("%b, %d %Y") %></td>
            <td><a href="<%= doctor_path(doctor) %>"><i class="small material-icons">account_box</i></a></td>
            <td><a href="<%= edit_doctor_path(doctor) %>"><i class="small material-icons">edit</i></a></td>
            <td><%= link_to content_tag('i', 'clear', class: 'small material-icons'), doctor, data: {confirm: "Are you sure you want to delete Dr. '#{doctor.name}'?"}, method: :delete %></td>
        </tr>
    <% end %>
</table>
</div>

app/views/doctors/new.html.erb
<div class="container">
    <p class="flow-text">Add a new physician</p>
    <%= render 'doctors/form'%>
</div>

app/views/doctors/show.html.erb
<div class="container">
    <p class="flow-text">Dr. <%= @doctor.name %>'s in-patients</p>
    <%= link_to content_tag('i', 'add', class: 'small material-icons'), patients_new_path(:doctor_id => @doctor.id), data: {confirm:"Admit a new patient?"} %>
    <br/>
    <br/>
    <table class="highlight">
        <tr>
            <th>MRN</th>
            <th>Patient's Name</th>
            <th>Age</th>
            <th>Gender</th>
            <th>Admission Date</th>
            <th>Bed No.</th>
        </tr>

        <% @patients.each do |patient| %>
        <tr>
            <th><%= patient.mrn %></th>
            <th><%= patient.name %></th>
            <th><%= patient.age %></th>
            <th><%= patient.gen %></th>
            <th><%= patient.created_at.strftime("%d-%m-%Y") %></th>
            <th><%= patient.bed_no %></th>
            <td><%= link_to content_tag('i', 'clear', class: 'small material-icons'), patient, data: {confirm: "Are you sure you want to delete '#{patient.name}'?"}, method: :delete %></td>
        </tr>
        <% end %>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>HospitalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <div class="container">
    <nav>
    <div class="nav-wrapper" style="background-color:#00695c">
      <div class="brand-logo">Hospital App</div>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to content_tag('i', 'home', class: 'small material-icons'), root_path, data: {} %></li>
        <li><%= link_to content_tag('i', 'directions_walk', class: 'small material-icons'), destroy_user_session_path, data: {confirm: "Are you sure you want to log out'?"}, method: :delete %></li>
      </ul>
    </div>
  </nav>
  </div>
  </header>

  <body style="background-color:#e0f2f1">
    <%= yield %>
  </body>
  
  <footer>
    <div class="footer-copyright">
      <div class="container">  
        <p class="grey-text right">< / > <span style="color:red">♥</span> by iFaisalo.</p>
      </div>
    </div>
  </footer>

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</html>

app/views/patients/_form.html.erb
<%= form_for @patient do |s| %>
<%= s.hidden_field :doctor_id, :value => @doctor.id %>
<div class="column">
    <form class="col s12">
        <div class="input-field col s2">
            <%= s.label :mrn, "MRN" %>
            <%= s.text_field :mrn %>
        </div>
        <div class="input-field col s2">
            <%= s.label :name, "Patient's Name" %>
            <%= s.text_field :name %>
        </div>
        <div class="input-field col s2">
            <%= s.label :age, "Age" %>
            <%= s.text_field :age %>
        </div>
        <div class="input-field col s2">
            <%= s.label :gen, "Gender" %>
            <%= s.text_field :gen %>
        </div>
        <div class="input-field col s2">
            <%= s.label :bed_no, "Bed No." %>
            <%= s.text_field :bed_no %>
        </div>
    </form>
    <%= s.submit "Submit", :class => "btn waves-effect waves-light"%>
</div>
<% end %>

app/views/patients/new.html.erb
<div class="container">
    <p class="flow-text">Admitting a new patient, under the care of Dr. <%= @doctor.name %></p>
    <%= render 'patients/form'%>
</div>